name: data_deal_dev
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  db: "news"
log:
  level: "debug"
  filename: "deal_news.log"
  max_size: 200
  max_age: 30
  max_backups: 5
mq:
  host: localhost
  port: 5673
queue:
  queueName: news_comment1
  durable: True
  autoDelete: False
  exclusive: False
  noWait: False
exchange:
  exchangeName: news_comment1
  kind: fanout
  durable: True
  autoDelete: False
  internal: False
  noWait: Fals


